{
 "title": "EUM Focus On Single Page",
 "description": "End-User-Monitoring information (focus on single page) collected by inspectIT.",
 "tags": [ "inspectit" ],
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pageUrl",
    "label": "Page",
    "query": "SHOW TAG VALUES FROM \"eum_browser_pageload\" WITH KEY = \"url\""
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Speedindex",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT median(\"speedindex\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT max(\"speedindex\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT min(\"speedindex\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  },
  {
   "title": "Resource Loading Initiators",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_initiatorType",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "initiatorType" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_resourceload",
     "query": "SELECT count(\"duration\") FROM \"eum_browser_resourceload\" WHERE \"initiatorUrl\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval),\"initiatorType\" fill(null)",
     "select": [
      [
       { "params": [ "initiatorType" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "initiatorUrl", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  },
  {
   "title": "Speedindex",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT median(\"speedindex\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  },
  {
   "title": "FirstPaint",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT median(\"firstpaint\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "firstpaint" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  },
  {
   "title": "DOMContentLoadedTime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT median(\"domContentLoadedEventEnd\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/   AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "domContentLoadedEventEnd" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT max(\"domContentLoadedEventEnd\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/   AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "domContentLoadedEventEnd" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT min(\"domContentLoadedEventEnd\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/  AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "domContentLoadedEventEnd" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT count(\"firstpaint\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/   AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "browser" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  },
  {
   "title": "Navigation Timings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "DNS Lookup",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT median(\"domainLookupEnd\")  - median(\"domainLookupStart\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "domainLookupStart" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "TCP Handshake",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"connectEnd\")  - median(\"connectStart\") FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "connectEnd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    },
    {
     "alias": "Response Transmission",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT median(\"responseEnd\") - median(\"responseStart\")  FROM \"eum_browser_pageload\" WHERE \"url\" =~ /^$pageUrl$/ AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "connectEnd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$page$/" }
     ]
    }
   ]
  }
 ]
}