{
 "title": "EUM Summary",
 "description": "End-User-Monitorig information collected by inspectIT.",
 "tags": [ "inspectit" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Users",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_user_region_code",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "user_region_code" ], "type": "tag" }
     ],
     "measurement": "users",
     "query": "SELECT mean(\"active_users\") AS \"metric\" FROM \"users\" WHERE $timeFilter GROUP BY time($interval), \"user_region_code\"",
     "select": [
      [
       { "params": [ "active_users" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pages Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SHOW TAG VALUES FROM \"eum_browser_pageload\" WITH KEY = \"url\"",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Speedindex", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Avg. Speedindex",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Speedindex (All Pages)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "speedindex",
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Speedindex Firefox",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE \"browser\" = 'Firefox' AND $timeFilter",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=", "value": "Firefox" }
     ]
    }
   ]
  },
  {
   "title": "Avg. Speedindex IE / Edge",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE \"browser\" = 'Internet Explorer' OR \"browser\" = 'Edge' AND $timeFilter",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=", "value": "Internet Explorer" },
      { "condition": "OR", "key": "browser", "operator": "=", "value": "Edge" }
     ]
    }
   ]
  },
  {
   "title": "Speedindex per Browser",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_browser (Desktop)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE $timeFilter AND \"device\"  =~ /Windows|Linux|Mac/ GROUP BY time($interval), \"browser\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_browser (Mobile)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE $timeFilter AND \"device\"  =~ /Android|iOS/ GROUP BY time($interval), \"browser\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_browser (Unknown OS)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE $timeFilter AND \"device\"  =~ /Unknown/ GROUP BY time($interval), \"browser\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Speedindex Chrome",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE \"browser\" = 'Google Chrome' AND $timeFilter",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=", "value": "Google Chrome" }
     ]
    }
   ]
  },
  {
   "title": "Avg. Speedindex Opera",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"speedindex\") FROM \"eum_browser_pageload\" WHERE \"browser\" = 'Opera' AND $timeFilter",
     "select": [
      [
       { "params": [ "speedindex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=", "value": "Opera" }
     ]
    }
   ]
  },
  {
   "title": "Ajax Calls | Navigation Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Avg. Ajax Duration",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "eum_browser_ajax",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Ajax Duration Chrome",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 21 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_ajax",
     "query": "SELECT median(count(\"url\")) FROM \"eum_browser_ajax\" WHERE $timeFilter GROUP BY  \"url\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=", "value": "Google Chrome" }
     ]
    }
   ]
  },
  {
   "title": "Avg. Ajax Duration IE / Edge",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 21 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_ajax",
     "query": "SELECT median(count(\"url\")) FROM \"eum_browser_ajax\" WHERE $timeFilter GROUP BY  \"url\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=", "value": "Internet Explorer" },
      { "condition": "OR", "key": "browser", "operator": "=", "value": "Edge" }
     ]
    }
   ]
  },
  {
   "title": "Navigation Timings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "eum_browser_pageload",
     "query": "SELECT mean(\"loadEventEnd\") AS \"Load Event End\" , mean(\"firstpaint\") AS \"First Paint\", mean(\"responseStart\") AS \"Response Start\" FROM \"eum_browser_pageload\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "loadEventEnd" ], "type": "field" }
      ],
      [
       { "params": [ "firstpaint" ], "type": "field" }
      ],
      [
       { "params": [ "responseStart" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Ajax Duration Firefox",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_ajax",
     "query": "SELECT median(count(\"url\")) FROM \"eum_browser_ajax\" WHERE $timeFilter GROUP BY  \"url\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=", "value": "Firefox" }
     ]
    }
   ]
  },
  {
   "title": "Avg. Ajax Duration Opera",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "eum_browser_ajax",
     "query": "SELECT median(count(\"url\")) FROM \"eum_browser_ajax\" WHERE $timeFilter GROUP BY  \"url\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "browser", "operator": "=", "value": "Opera" }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. Resources per Pageload",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 21 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "eum_browser_pageload",
       "query": "SELECT mean(\"resourceCount\") FROM \"eum_browser_pageload\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "resourceCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Resource Load Time Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 12, "w": 6, "x": 4, "y": 21 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "alias": "$tag_initiatorType",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"duration\") AS metric FROM \"eum_browser_resourceload\" WHERE $timeFilter GROUP BY time($interval), \"initiatorType\" fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "metric" ], "type": "alias" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Average Resource Loading Time per Type",
     "type": "graph",
     "gridPos": { "h": 12, "w": 14, "x": 10, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_initiatorType",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "eum_browser_resourceload",
       "query": "SELECT mean(\"duration\") FROM \"eum_browser_resourceload\" WHERE $timeFilter GROUP BY time($interval), \"initiatorType\" fill(none)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "initiatorType", "operator": "=", "value": "css" }
       ]
      }
     ]
    },
    {
     "title": "Avg. Loading Time per Resource",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "eum_browser_resourceload",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Max. Resource Loading Time",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
     "format": "ms",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "eum_browser_resourceload",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}